apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tehfeelz
spec:
  project: tehfeelz
  source:
    repoURL: https://github.com/unifist/platform
    path: unums/{{ unum }}/apps/tehfeelz
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: tehfeelz
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
