apiVersion: apps/v1
kind: Deployment
metadata:
  name: gui
  namespace: feelz
spec:
  template:
    spec:
      containers:
      - name: gui
        image: unum-apps-feelz-gui
        imagePullPolicy: Never
